# Generated by Django 5.0.6 on 2024-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=500)),
                ('breeds', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=200)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'pet',
            },
        ),
    ]
