# Generated by Django 5.0.6 on 2024-06-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
