# Generated by Django 5.0.6 on 2024-06-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='paymentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.payment'),
        ),
    ]
